/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: 416f5f68a787d4cd179e854ffb58ba0b)
declare namespace Cloudflare {
	interface Env {
		PANCHANGAM_CACHE: KVNamespace;
		PANCHANGAM_DB: D1Database;
		OPENCAGE_API_KEY: string;
		CLOUDFLARE_D1_DATABASE_ID: string;
		CLOUDFLARE_KV_NAMESPACE: string;
		RESEND_API_KEY: string;
		RESEND_FROM_EMAIL: string;
	}
}
interface Env extends Cloudflare.Env {}
