"""001 — Initial schema (raw SQL from spec/db/)

Run order:
  1. schema.sql  — 41 tables + indexes (btree_gist + pgcrypto required)
  2. triggers.sql — 5 trigger functions (v2.1)
  3. seed.sql    — required status_types rows (deployment gate)

DO NOT edit this file. If you need to change schema, write migration 004+.
"""
from pathlib import Path
from alembic import op

revision = "001"
down_revision = None
branch_labels = None
depends_on = None

DB_DIR = Path(__file__).parent.parent.parent / "spec" / "db"


def upgrade() -> None:
    for filename in ("schema.sql", "triggers.sql", "seed.sql"):
        sql = (DB_DIR / filename).read_text()
        op.execute(sql)  # type: ignore[arg-type]


def downgrade() -> None:
    # Irreversible — this is the initial schema.
    # To start fresh, drop and recreate the database.
    raise NotImplementedError("Migration 001 is irreversible. Drop and recreate the DB.")
